# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/civmap/proto/civmap.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from message.common.proto import header_pb2 as message_dot_common_dot_proto_dot_header__pb2
from message.map.proto import map_pb2 as message_dot_map_dot_proto_dot_map__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/civmap/proto/civmap.proto',
  package='civ.civmap',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!message/civmap/proto/civmap.proto\x12\nciv.civmap\x1a!message/common/proto/header.proto\x1a\x1bmessage/map/proto/map.proto\"N\n\x0bZmapMessage\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.civ.common.Header\x12\x1b\n\x03map\x18\x02 \x01(\x0b\x32\x0e.civ.hdmap.Map'
  ,
  dependencies=[message_dot_common_dot_proto_dot_header__pb2.DESCRIPTOR,message_dot_map_dot_proto_dot_map__pb2.DESCRIPTOR,])




_ZMAPMESSAGE = _descriptor.Descriptor(
  name='ZmapMessage',
  full_name='civ.civmap.ZmapMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='civ.civmap.ZmapMessage.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='map', full_name='civ.civmap.ZmapMessage.map', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=191,
)

_ZMAPMESSAGE.fields_by_name['header'].message_type = message_dot_common_dot_proto_dot_header__pb2._HEADER
_ZMAPMESSAGE.fields_by_name['map'].message_type = message_dot_map_dot_proto_dot_map__pb2._MAP
DESCRIPTOR.message_types_by_name['ZmapMessage'] = _ZMAPMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ZmapMessage = _reflection.GeneratedProtocolMessageType('ZmapMessage', (_message.Message,), {
  'DESCRIPTOR' : _ZMAPMESSAGE,
  '__module__' : 'message.civmap.proto.civmap_pb2'
  # @@protoc_insertion_point(class_scope:civ.civmap.ZmapMessage)
  })
_sym_db.RegisterMessage(ZmapMessage)


# @@protoc_insertion_point(module_scope)
