// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message/map/proto/map.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_message_2fmap_2fproto_2fmap_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_message_2fmap_2fproto_2fmap_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "message/map/proto/map_clear_area.pb.h"
#include "message/map/proto/map_crosswalk.pb.h"
#include "message/map/proto/map_junction.pb.h"
#include "message/map/proto/map_lane.pb.h"
#include "message/map/proto/map_overlap.pb.h"
#include "message/map/proto/map_signal.pb.h"
#include "message/map/proto/map_speed_bump.pb.h"
#include "message/map/proto/map_stop_sign.pb.h"
#include "message/map/proto/map_yield_sign.pb.h"
#include "message/map/proto/map_road.pb.h"
#include "message/map/proto/map_parking_space.pb.h"
#include "message/map/proto/map_pnc_junction.pb.h"
#include "message/map/proto/map_rsu.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_message_2fmap_2fproto_2fmap_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_message_2fmap_2fproto_2fmap_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_2fmap_2fproto_2fmap_2eproto;
namespace civ {
namespace hdmap {
class Header;
class HeaderDefaultTypeInternal;
extern HeaderDefaultTypeInternal _Header_default_instance_;
class Map;
class MapDefaultTypeInternal;
extern MapDefaultTypeInternal _Map_default_instance_;
class Projection;
class ProjectionDefaultTypeInternal;
extern ProjectionDefaultTypeInternal _Projection_default_instance_;
}  // namespace hdmap
}  // namespace civ
PROTOBUF_NAMESPACE_OPEN
template<> ::civ::hdmap::Header* Arena::CreateMaybeMessage<::civ::hdmap::Header>(Arena*);
template<> ::civ::hdmap::Map* Arena::CreateMaybeMessage<::civ::hdmap::Map>(Arena*);
template<> ::civ::hdmap::Projection* Arena::CreateMaybeMessage<::civ::hdmap::Projection>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace civ {
namespace hdmap {

// ===================================================================

class Projection PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:civ.hdmap.Projection) */ {
 public:
  inline Projection() : Projection(nullptr) {}
  virtual ~Projection();

  Projection(const Projection& from);
  Projection(Projection&& from) noexcept
    : Projection() {
    *this = ::std::move(from);
  }

  inline Projection& operator=(const Projection& from) {
    CopyFrom(from);
    return *this;
  }
  inline Projection& operator=(Projection&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Projection& default_instance();

  static inline const Projection* internal_default_instance() {
    return reinterpret_cast<const Projection*>(
               &_Projection_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Projection& a, Projection& b) {
    a.Swap(&b);
  }
  inline void Swap(Projection* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Projection* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Projection* New() const final {
    return CreateMaybeMessage<Projection>(nullptr);
  }

  Projection* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Projection>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Projection& from);
  void MergeFrom(const Projection& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Projection* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "civ.hdmap.Projection";
  }
  protected:
  explicit Projection(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2fmap_2fproto_2fmap_2eproto);
    return ::descriptor_table_message_2fmap_2fproto_2fmap_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kProjFieldNumber = 1,
    kOriginLatitudeDegFieldNumber = 2,
    kOriginLongitudeDegFieldNumber = 3,
    kOriginAltitudeMFieldNumber = 4,
  };
  // optional string proj = 1;
  bool has_proj() const;
  private:
  bool _internal_has_proj() const;
  public:
  void clear_proj();
  const std::string& proj() const;
  void set_proj(const std::string& value);
  void set_proj(std::string&& value);
  void set_proj(const char* value);
  void set_proj(const char* value, size_t size);
  std::string* mutable_proj();
  std::string* release_proj();
  void set_allocated_proj(std::string* proj);
  private:
  const std::string& _internal_proj() const;
  void _internal_set_proj(const std::string& value);
  std::string* _internal_mutable_proj();
  public:

  // optional double origin_latitude_deg = 2 [default = 0];
  bool has_origin_latitude_deg() const;
  private:
  bool _internal_has_origin_latitude_deg() const;
  public:
  void clear_origin_latitude_deg();
  double origin_latitude_deg() const;
  void set_origin_latitude_deg(double value);
  private:
  double _internal_origin_latitude_deg() const;
  void _internal_set_origin_latitude_deg(double value);
  public:

  // optional double origin_longitude_deg = 3 [default = 0];
  bool has_origin_longitude_deg() const;
  private:
  bool _internal_has_origin_longitude_deg() const;
  public:
  void clear_origin_longitude_deg();
  double origin_longitude_deg() const;
  void set_origin_longitude_deg(double value);
  private:
  double _internal_origin_longitude_deg() const;
  void _internal_set_origin_longitude_deg(double value);
  public:

  // optional double origin_altitude_m = 4 [default = 0];
  bool has_origin_altitude_m() const;
  private:
  bool _internal_has_origin_altitude_m() const;
  public:
  void clear_origin_altitude_m();
  double origin_altitude_m() const;
  void set_origin_altitude_m(double value);
  private:
  double _internal_origin_altitude_m() const;
  void _internal_set_origin_altitude_m(double value);
  public:

  // @@protoc_insertion_point(class_scope:civ.hdmap.Projection)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr proj_;
  double origin_latitude_deg_;
  double origin_longitude_deg_;
  double origin_altitude_m_;
  friend struct ::TableStruct_message_2fmap_2fproto_2fmap_2eproto;
};
// -------------------------------------------------------------------

class Header PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:civ.hdmap.Header) */ {
 public:
  inline Header() : Header(nullptr) {}
  virtual ~Header();

  Header(const Header& from);
  Header(Header&& from) noexcept
    : Header() {
    *this = ::std::move(from);
  }

  inline Header& operator=(const Header& from) {
    CopyFrom(from);
    return *this;
  }
  inline Header& operator=(Header&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Header& default_instance();

  static inline const Header* internal_default_instance() {
    return reinterpret_cast<const Header*>(
               &_Header_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Header& a, Header& b) {
    a.Swap(&b);
  }
  inline void Swap(Header* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Header* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Header* New() const final {
    return CreateMaybeMessage<Header>(nullptr);
  }

  Header* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Header>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Header& from);
  void MergeFrom(const Header& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Header* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "civ.hdmap.Header";
  }
  protected:
  explicit Header(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2fmap_2fproto_2fmap_2eproto);
    return ::descriptor_table_message_2fmap_2fproto_2fmap_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVersionFieldNumber = 1,
    kDateFieldNumber = 2,
    kDistrictFieldNumber = 4,
    kGenerationFieldNumber = 5,
    kRevMajorFieldNumber = 6,
    kRevMinorFieldNumber = 7,
    kVendorFieldNumber = 12,
    kProjectionFieldNumber = 3,
    kLeftFieldNumber = 8,
    kTopFieldNumber = 9,
    kRightFieldNumber = 10,
    kBottomFieldNumber = 11,
  };
  // optional bytes version = 1;
  bool has_version() const;
  private:
  bool _internal_has_version() const;
  public:
  void clear_version();
  const std::string& version() const;
  void set_version(const std::string& value);
  void set_version(std::string&& value);
  void set_version(const char* value);
  void set_version(const void* value, size_t size);
  std::string* mutable_version();
  std::string* release_version();
  void set_allocated_version(std::string* version);
  private:
  const std::string& _internal_version() const;
  void _internal_set_version(const std::string& value);
  std::string* _internal_mutable_version();
  public:

  // optional bytes date = 2;
  bool has_date() const;
  private:
  bool _internal_has_date() const;
  public:
  void clear_date();
  const std::string& date() const;
  void set_date(const std::string& value);
  void set_date(std::string&& value);
  void set_date(const char* value);
  void set_date(const void* value, size_t size);
  std::string* mutable_date();
  std::string* release_date();
  void set_allocated_date(std::string* date);
  private:
  const std::string& _internal_date() const;
  void _internal_set_date(const std::string& value);
  std::string* _internal_mutable_date();
  public:

  // optional bytes district = 4;
  bool has_district() const;
  private:
  bool _internal_has_district() const;
  public:
  void clear_district();
  const std::string& district() const;
  void set_district(const std::string& value);
  void set_district(std::string&& value);
  void set_district(const char* value);
  void set_district(const void* value, size_t size);
  std::string* mutable_district();
  std::string* release_district();
  void set_allocated_district(std::string* district);
  private:
  const std::string& _internal_district() const;
  void _internal_set_district(const std::string& value);
  std::string* _internal_mutable_district();
  public:

  // optional bytes generation = 5;
  bool has_generation() const;
  private:
  bool _internal_has_generation() const;
  public:
  void clear_generation();
  const std::string& generation() const;
  void set_generation(const std::string& value);
  void set_generation(std::string&& value);
  void set_generation(const char* value);
  void set_generation(const void* value, size_t size);
  std::string* mutable_generation();
  std::string* release_generation();
  void set_allocated_generation(std::string* generation);
  private:
  const std::string& _internal_generation() const;
  void _internal_set_generation(const std::string& value);
  std::string* _internal_mutable_generation();
  public:

  // optional bytes rev_major = 6;
  bool has_rev_major() const;
  private:
  bool _internal_has_rev_major() const;
  public:
  void clear_rev_major();
  const std::string& rev_major() const;
  void set_rev_major(const std::string& value);
  void set_rev_major(std::string&& value);
  void set_rev_major(const char* value);
  void set_rev_major(const void* value, size_t size);
  std::string* mutable_rev_major();
  std::string* release_rev_major();
  void set_allocated_rev_major(std::string* rev_major);
  private:
  const std::string& _internal_rev_major() const;
  void _internal_set_rev_major(const std::string& value);
  std::string* _internal_mutable_rev_major();
  public:

  // optional bytes rev_minor = 7;
  bool has_rev_minor() const;
  private:
  bool _internal_has_rev_minor() const;
  public:
  void clear_rev_minor();
  const std::string& rev_minor() const;
  void set_rev_minor(const std::string& value);
  void set_rev_minor(std::string&& value);
  void set_rev_minor(const char* value);
  void set_rev_minor(const void* value, size_t size);
  std::string* mutable_rev_minor();
  std::string* release_rev_minor();
  void set_allocated_rev_minor(std::string* rev_minor);
  private:
  const std::string& _internal_rev_minor() const;
  void _internal_set_rev_minor(const std::string& value);
  std::string* _internal_mutable_rev_minor();
  public:

  // optional bytes vendor = 12;
  bool has_vendor() const;
  private:
  bool _internal_has_vendor() const;
  public:
  void clear_vendor();
  const std::string& vendor() const;
  void set_vendor(const std::string& value);
  void set_vendor(std::string&& value);
  void set_vendor(const char* value);
  void set_vendor(const void* value, size_t size);
  std::string* mutable_vendor();
  std::string* release_vendor();
  void set_allocated_vendor(std::string* vendor);
  private:
  const std::string& _internal_vendor() const;
  void _internal_set_vendor(const std::string& value);
  std::string* _internal_mutable_vendor();
  public:

  // optional .civ.hdmap.Projection projection = 3;
  bool has_projection() const;
  private:
  bool _internal_has_projection() const;
  public:
  void clear_projection();
  const ::civ::hdmap::Projection& projection() const;
  ::civ::hdmap::Projection* release_projection();
  ::civ::hdmap::Projection* mutable_projection();
  void set_allocated_projection(::civ::hdmap::Projection* projection);
  private:
  const ::civ::hdmap::Projection& _internal_projection() const;
  ::civ::hdmap::Projection* _internal_mutable_projection();
  public:
  void unsafe_arena_set_allocated_projection(
      ::civ::hdmap::Projection* projection);
  ::civ::hdmap::Projection* unsafe_arena_release_projection();

  // optional double left = 8;
  bool has_left() const;
  private:
  bool _internal_has_left() const;
  public:
  void clear_left();
  double left() const;
  void set_left(double value);
  private:
  double _internal_left() const;
  void _internal_set_left(double value);
  public:

  // optional double top = 9;
  bool has_top() const;
  private:
  bool _internal_has_top() const;
  public:
  void clear_top();
  double top() const;
  void set_top(double value);
  private:
  double _internal_top() const;
  void _internal_set_top(double value);
  public:

  // optional double right = 10;
  bool has_right() const;
  private:
  bool _internal_has_right() const;
  public:
  void clear_right();
  double right() const;
  void set_right(double value);
  private:
  double _internal_right() const;
  void _internal_set_right(double value);
  public:

  // optional double bottom = 11;
  bool has_bottom() const;
  private:
  bool _internal_has_bottom() const;
  public:
  void clear_bottom();
  double bottom() const;
  void set_bottom(double value);
  private:
  double _internal_bottom() const;
  void _internal_set_bottom(double value);
  public:

  // @@protoc_insertion_point(class_scope:civ.hdmap.Header)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr version_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr date_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr district_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr generation_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr rev_major_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr rev_minor_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr vendor_;
  ::civ::hdmap::Projection* projection_;
  double left_;
  double top_;
  double right_;
  double bottom_;
  friend struct ::TableStruct_message_2fmap_2fproto_2fmap_2eproto;
};
// -------------------------------------------------------------------

class Map PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:civ.hdmap.Map) */ {
 public:
  inline Map() : Map(nullptr) {}
  virtual ~Map();

  Map(const Map& from);
  Map(Map&& from) noexcept
    : Map() {
    *this = ::std::move(from);
  }

  inline Map& operator=(const Map& from) {
    CopyFrom(from);
    return *this;
  }
  inline Map& operator=(Map&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Map& default_instance();

  static inline const Map* internal_default_instance() {
    return reinterpret_cast<const Map*>(
               &_Map_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Map& a, Map& b) {
    a.Swap(&b);
  }
  inline void Swap(Map* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Map* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Map* New() const final {
    return CreateMaybeMessage<Map>(nullptr);
  }

  Map* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Map>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Map& from);
  void MergeFrom(const Map& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Map* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "civ.hdmap.Map";
  }
  protected:
  explicit Map(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2fmap_2fproto_2fmap_2eproto);
    return ::descriptor_table_message_2fmap_2fproto_2fmap_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCrosswalkFieldNumber = 2,
    kJunctionFieldNumber = 3,
    kLaneFieldNumber = 4,
    kStopSignFieldNumber = 5,
    kSignalFieldNumber = 6,
    kYieldFieldNumber = 7,
    kOverlapFieldNumber = 8,
    kClearAreaFieldNumber = 9,
    kSpeedBumpFieldNumber = 10,
    kRoadFieldNumber = 11,
    kParkingSpaceFieldNumber = 12,
    kPncJunctionFieldNumber = 13,
    kRsuFieldNumber = 14,
    kHeaderFieldNumber = 1,
  };
  // repeated .civ.hdmap.Crosswalk crosswalk = 2;
  int crosswalk_size() const;
  private:
  int _internal_crosswalk_size() const;
  public:
  void clear_crosswalk();
  ::civ::hdmap::Crosswalk* mutable_crosswalk(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Crosswalk >*
      mutable_crosswalk();
  private:
  const ::civ::hdmap::Crosswalk& _internal_crosswalk(int index) const;
  ::civ::hdmap::Crosswalk* _internal_add_crosswalk();
  public:
  const ::civ::hdmap::Crosswalk& crosswalk(int index) const;
  ::civ::hdmap::Crosswalk* add_crosswalk();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Crosswalk >&
      crosswalk() const;

  // repeated .civ.hdmap.Junction junction = 3;
  int junction_size() const;
  private:
  int _internal_junction_size() const;
  public:
  void clear_junction();
  ::civ::hdmap::Junction* mutable_junction(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Junction >*
      mutable_junction();
  private:
  const ::civ::hdmap::Junction& _internal_junction(int index) const;
  ::civ::hdmap::Junction* _internal_add_junction();
  public:
  const ::civ::hdmap::Junction& junction(int index) const;
  ::civ::hdmap::Junction* add_junction();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Junction >&
      junction() const;

  // repeated .civ.hdmap.Lane lane = 4;
  int lane_size() const;
  private:
  int _internal_lane_size() const;
  public:
  void clear_lane();
  ::civ::hdmap::Lane* mutable_lane(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Lane >*
      mutable_lane();
  private:
  const ::civ::hdmap::Lane& _internal_lane(int index) const;
  ::civ::hdmap::Lane* _internal_add_lane();
  public:
  const ::civ::hdmap::Lane& lane(int index) const;
  ::civ::hdmap::Lane* add_lane();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Lane >&
      lane() const;

  // repeated .civ.hdmap.StopSign stop_sign = 5;
  int stop_sign_size() const;
  private:
  int _internal_stop_sign_size() const;
  public:
  void clear_stop_sign();
  ::civ::hdmap::StopSign* mutable_stop_sign(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::StopSign >*
      mutable_stop_sign();
  private:
  const ::civ::hdmap::StopSign& _internal_stop_sign(int index) const;
  ::civ::hdmap::StopSign* _internal_add_stop_sign();
  public:
  const ::civ::hdmap::StopSign& stop_sign(int index) const;
  ::civ::hdmap::StopSign* add_stop_sign();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::StopSign >&
      stop_sign() const;

  // repeated .civ.hdmap.Signal signal = 6;
  int signal_size() const;
  private:
  int _internal_signal_size() const;
  public:
  void clear_signal();
  ::civ::hdmap::Signal* mutable_signal(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Signal >*
      mutable_signal();
  private:
  const ::civ::hdmap::Signal& _internal_signal(int index) const;
  ::civ::hdmap::Signal* _internal_add_signal();
  public:
  const ::civ::hdmap::Signal& signal(int index) const;
  ::civ::hdmap::Signal* add_signal();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Signal >&
      signal() const;

  // repeated .civ.hdmap.YieldSign yield = 7;
  int yield_size() const;
  private:
  int _internal_yield_size() const;
  public:
  void clear_yield();
  ::civ::hdmap::YieldSign* mutable_yield(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::YieldSign >*
      mutable_yield();
  private:
  const ::civ::hdmap::YieldSign& _internal_yield(int index) const;
  ::civ::hdmap::YieldSign* _internal_add_yield();
  public:
  const ::civ::hdmap::YieldSign& yield(int index) const;
  ::civ::hdmap::YieldSign* add_yield();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::YieldSign >&
      yield() const;

  // repeated .civ.hdmap.Overlap overlap = 8;
  int overlap_size() const;
  private:
  int _internal_overlap_size() const;
  public:
  void clear_overlap();
  ::civ::hdmap::Overlap* mutable_overlap(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Overlap >*
      mutable_overlap();
  private:
  const ::civ::hdmap::Overlap& _internal_overlap(int index) const;
  ::civ::hdmap::Overlap* _internal_add_overlap();
  public:
  const ::civ::hdmap::Overlap& overlap(int index) const;
  ::civ::hdmap::Overlap* add_overlap();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Overlap >&
      overlap() const;

  // repeated .civ.hdmap.ClearArea clear_area = 9;
  int clear_area_size() const;
  private:
  int _internal_clear_area_size() const;
  public:
  void clear_clear_area();
  ::civ::hdmap::ClearArea* mutable_clear_area(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::ClearArea >*
      mutable_clear_area();
  private:
  const ::civ::hdmap::ClearArea& _internal_clear_area(int index) const;
  ::civ::hdmap::ClearArea* _internal_add_clear_area();
  public:
  const ::civ::hdmap::ClearArea& clear_area(int index) const;
  ::civ::hdmap::ClearArea* add_clear_area();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::ClearArea >&
      clear_area() const;

  // repeated .civ.hdmap.SpeedBump speed_bump = 10;
  int speed_bump_size() const;
  private:
  int _internal_speed_bump_size() const;
  public:
  void clear_speed_bump();
  ::civ::hdmap::SpeedBump* mutable_speed_bump(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::SpeedBump >*
      mutable_speed_bump();
  private:
  const ::civ::hdmap::SpeedBump& _internal_speed_bump(int index) const;
  ::civ::hdmap::SpeedBump* _internal_add_speed_bump();
  public:
  const ::civ::hdmap::SpeedBump& speed_bump(int index) const;
  ::civ::hdmap::SpeedBump* add_speed_bump();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::SpeedBump >&
      speed_bump() const;

  // repeated .civ.hdmap.Road road = 11;
  int road_size() const;
  private:
  int _internal_road_size() const;
  public:
  void clear_road();
  ::civ::hdmap::Road* mutable_road(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Road >*
      mutable_road();
  private:
  const ::civ::hdmap::Road& _internal_road(int index) const;
  ::civ::hdmap::Road* _internal_add_road();
  public:
  const ::civ::hdmap::Road& road(int index) const;
  ::civ::hdmap::Road* add_road();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Road >&
      road() const;

  // repeated .civ.hdmap.ParkingSpace parking_space = 12;
  int parking_space_size() const;
  private:
  int _internal_parking_space_size() const;
  public:
  void clear_parking_space();
  ::civ::hdmap::ParkingSpace* mutable_parking_space(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::ParkingSpace >*
      mutable_parking_space();
  private:
  const ::civ::hdmap::ParkingSpace& _internal_parking_space(int index) const;
  ::civ::hdmap::ParkingSpace* _internal_add_parking_space();
  public:
  const ::civ::hdmap::ParkingSpace& parking_space(int index) const;
  ::civ::hdmap::ParkingSpace* add_parking_space();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::ParkingSpace >&
      parking_space() const;

  // repeated .civ.hdmap.PNCJunction pnc_junction = 13;
  int pnc_junction_size() const;
  private:
  int _internal_pnc_junction_size() const;
  public:
  void clear_pnc_junction();
  ::civ::hdmap::PNCJunction* mutable_pnc_junction(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::PNCJunction >*
      mutable_pnc_junction();
  private:
  const ::civ::hdmap::PNCJunction& _internal_pnc_junction(int index) const;
  ::civ::hdmap::PNCJunction* _internal_add_pnc_junction();
  public:
  const ::civ::hdmap::PNCJunction& pnc_junction(int index) const;
  ::civ::hdmap::PNCJunction* add_pnc_junction();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::PNCJunction >&
      pnc_junction() const;

  // repeated .civ.hdmap.RSU rsu = 14;
  int rsu_size() const;
  private:
  int _internal_rsu_size() const;
  public:
  void clear_rsu();
  ::civ::hdmap::RSU* mutable_rsu(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::RSU >*
      mutable_rsu();
  private:
  const ::civ::hdmap::RSU& _internal_rsu(int index) const;
  ::civ::hdmap::RSU* _internal_add_rsu();
  public:
  const ::civ::hdmap::RSU& rsu(int index) const;
  ::civ::hdmap::RSU* add_rsu();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::RSU >&
      rsu() const;

  // optional .civ.hdmap.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::civ::hdmap::Header& header() const;
  ::civ::hdmap::Header* release_header();
  ::civ::hdmap::Header* mutable_header();
  void set_allocated_header(::civ::hdmap::Header* header);
  private:
  const ::civ::hdmap::Header& _internal_header() const;
  ::civ::hdmap::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::civ::hdmap::Header* header);
  ::civ::hdmap::Header* unsafe_arena_release_header();

  // @@protoc_insertion_point(class_scope:civ.hdmap.Map)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Crosswalk > crosswalk_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Junction > junction_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Lane > lane_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::StopSign > stop_sign_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Signal > signal_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::YieldSign > yield_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Overlap > overlap_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::ClearArea > clear_area_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::SpeedBump > speed_bump_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Road > road_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::ParkingSpace > parking_space_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::PNCJunction > pnc_junction_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::RSU > rsu_;
  ::civ::hdmap::Header* header_;
  friend struct ::TableStruct_message_2fmap_2fproto_2fmap_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Projection

// optional string proj = 1;
inline bool Projection::_internal_has_proj() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Projection::has_proj() const {
  return _internal_has_proj();
}
inline void Projection::clear_proj() {
  proj_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Projection::proj() const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Projection.proj)
  return _internal_proj();
}
inline void Projection::set_proj(const std::string& value) {
  _internal_set_proj(value);
  // @@protoc_insertion_point(field_set:civ.hdmap.Projection.proj)
}
inline std::string* Projection::mutable_proj() {
  // @@protoc_insertion_point(field_mutable:civ.hdmap.Projection.proj)
  return _internal_mutable_proj();
}
inline const std::string& Projection::_internal_proj() const {
  return proj_.Get();
}
inline void Projection::_internal_set_proj(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  proj_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Projection::set_proj(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  proj_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:civ.hdmap.Projection.proj)
}
inline void Projection::set_proj(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  proj_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:civ.hdmap.Projection.proj)
}
inline void Projection::set_proj(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  proj_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:civ.hdmap.Projection.proj)
}
inline std::string* Projection::_internal_mutable_proj() {
  _has_bits_[0] |= 0x00000001u;
  return proj_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Projection::release_proj() {
  // @@protoc_insertion_point(field_release:civ.hdmap.Projection.proj)
  if (!_internal_has_proj()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return proj_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Projection::set_allocated_proj(std::string* proj) {
  if (proj != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  proj_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), proj,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:civ.hdmap.Projection.proj)
}

// optional double origin_latitude_deg = 2 [default = 0];
inline bool Projection::_internal_has_origin_latitude_deg() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Projection::has_origin_latitude_deg() const {
  return _internal_has_origin_latitude_deg();
}
inline void Projection::clear_origin_latitude_deg() {
  origin_latitude_deg_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline double Projection::_internal_origin_latitude_deg() const {
  return origin_latitude_deg_;
}
inline double Projection::origin_latitude_deg() const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Projection.origin_latitude_deg)
  return _internal_origin_latitude_deg();
}
inline void Projection::_internal_set_origin_latitude_deg(double value) {
  _has_bits_[0] |= 0x00000002u;
  origin_latitude_deg_ = value;
}
inline void Projection::set_origin_latitude_deg(double value) {
  _internal_set_origin_latitude_deg(value);
  // @@protoc_insertion_point(field_set:civ.hdmap.Projection.origin_latitude_deg)
}

// optional double origin_longitude_deg = 3 [default = 0];
inline bool Projection::_internal_has_origin_longitude_deg() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Projection::has_origin_longitude_deg() const {
  return _internal_has_origin_longitude_deg();
}
inline void Projection::clear_origin_longitude_deg() {
  origin_longitude_deg_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline double Projection::_internal_origin_longitude_deg() const {
  return origin_longitude_deg_;
}
inline double Projection::origin_longitude_deg() const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Projection.origin_longitude_deg)
  return _internal_origin_longitude_deg();
}
inline void Projection::_internal_set_origin_longitude_deg(double value) {
  _has_bits_[0] |= 0x00000004u;
  origin_longitude_deg_ = value;
}
inline void Projection::set_origin_longitude_deg(double value) {
  _internal_set_origin_longitude_deg(value);
  // @@protoc_insertion_point(field_set:civ.hdmap.Projection.origin_longitude_deg)
}

// optional double origin_altitude_m = 4 [default = 0];
inline bool Projection::_internal_has_origin_altitude_m() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Projection::has_origin_altitude_m() const {
  return _internal_has_origin_altitude_m();
}
inline void Projection::clear_origin_altitude_m() {
  origin_altitude_m_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline double Projection::_internal_origin_altitude_m() const {
  return origin_altitude_m_;
}
inline double Projection::origin_altitude_m() const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Projection.origin_altitude_m)
  return _internal_origin_altitude_m();
}
inline void Projection::_internal_set_origin_altitude_m(double value) {
  _has_bits_[0] |= 0x00000008u;
  origin_altitude_m_ = value;
}
inline void Projection::set_origin_altitude_m(double value) {
  _internal_set_origin_altitude_m(value);
  // @@protoc_insertion_point(field_set:civ.hdmap.Projection.origin_altitude_m)
}

// -------------------------------------------------------------------

// Header

// optional bytes version = 1;
inline bool Header::_internal_has_version() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Header::has_version() const {
  return _internal_has_version();
}
inline void Header::clear_version() {
  version_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Header::version() const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Header.version)
  return _internal_version();
}
inline void Header::set_version(const std::string& value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:civ.hdmap.Header.version)
}
inline std::string* Header::mutable_version() {
  // @@protoc_insertion_point(field_mutable:civ.hdmap.Header.version)
  return _internal_mutable_version();
}
inline const std::string& Header::_internal_version() const {
  return version_.Get();
}
inline void Header::_internal_set_version(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  version_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Header::set_version(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  version_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:civ.hdmap.Header.version)
}
inline void Header::set_version(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  version_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:civ.hdmap.Header.version)
}
inline void Header::set_version(const void* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  version_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:civ.hdmap.Header.version)
}
inline std::string* Header::_internal_mutable_version() {
  _has_bits_[0] |= 0x00000001u;
  return version_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Header::release_version() {
  // @@protoc_insertion_point(field_release:civ.hdmap.Header.version)
  if (!_internal_has_version()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return version_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Header::set_allocated_version(std::string* version) {
  if (version != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  version_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), version,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:civ.hdmap.Header.version)
}

// optional bytes date = 2;
inline bool Header::_internal_has_date() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Header::has_date() const {
  return _internal_has_date();
}
inline void Header::clear_date() {
  date_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Header::date() const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Header.date)
  return _internal_date();
}
inline void Header::set_date(const std::string& value) {
  _internal_set_date(value);
  // @@protoc_insertion_point(field_set:civ.hdmap.Header.date)
}
inline std::string* Header::mutable_date() {
  // @@protoc_insertion_point(field_mutable:civ.hdmap.Header.date)
  return _internal_mutable_date();
}
inline const std::string& Header::_internal_date() const {
  return date_.Get();
}
inline void Header::_internal_set_date(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  date_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Header::set_date(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  date_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:civ.hdmap.Header.date)
}
inline void Header::set_date(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  date_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:civ.hdmap.Header.date)
}
inline void Header::set_date(const void* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  date_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:civ.hdmap.Header.date)
}
inline std::string* Header::_internal_mutable_date() {
  _has_bits_[0] |= 0x00000002u;
  return date_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Header::release_date() {
  // @@protoc_insertion_point(field_release:civ.hdmap.Header.date)
  if (!_internal_has_date()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return date_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Header::set_allocated_date(std::string* date) {
  if (date != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  date_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), date,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:civ.hdmap.Header.date)
}

// optional .civ.hdmap.Projection projection = 3;
inline bool Header::_internal_has_projection() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  PROTOBUF_ASSUME(!value || projection_ != nullptr);
  return value;
}
inline bool Header::has_projection() const {
  return _internal_has_projection();
}
inline void Header::clear_projection() {
  if (projection_ != nullptr) projection_->Clear();
  _has_bits_[0] &= ~0x00000080u;
}
inline const ::civ::hdmap::Projection& Header::_internal_projection() const {
  const ::civ::hdmap::Projection* p = projection_;
  return p != nullptr ? *p : reinterpret_cast<const ::civ::hdmap::Projection&>(
      ::civ::hdmap::_Projection_default_instance_);
}
inline const ::civ::hdmap::Projection& Header::projection() const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Header.projection)
  return _internal_projection();
}
inline void Header::unsafe_arena_set_allocated_projection(
    ::civ::hdmap::Projection* projection) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(projection_);
  }
  projection_ = projection;
  if (projection) {
    _has_bits_[0] |= 0x00000080u;
  } else {
    _has_bits_[0] &= ~0x00000080u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:civ.hdmap.Header.projection)
}
inline ::civ::hdmap::Projection* Header::release_projection() {
  _has_bits_[0] &= ~0x00000080u;
  ::civ::hdmap::Projection* temp = projection_;
  projection_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::civ::hdmap::Projection* Header::unsafe_arena_release_projection() {
  // @@protoc_insertion_point(field_release:civ.hdmap.Header.projection)
  _has_bits_[0] &= ~0x00000080u;
  ::civ::hdmap::Projection* temp = projection_;
  projection_ = nullptr;
  return temp;
}
inline ::civ::hdmap::Projection* Header::_internal_mutable_projection() {
  _has_bits_[0] |= 0x00000080u;
  if (projection_ == nullptr) {
    auto* p = CreateMaybeMessage<::civ::hdmap::Projection>(GetArena());
    projection_ = p;
  }
  return projection_;
}
inline ::civ::hdmap::Projection* Header::mutable_projection() {
  // @@protoc_insertion_point(field_mutable:civ.hdmap.Header.projection)
  return _internal_mutable_projection();
}
inline void Header::set_allocated_projection(::civ::hdmap::Projection* projection) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete projection_;
  }
  if (projection) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(projection);
    if (message_arena != submessage_arena) {
      projection = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, projection, submessage_arena);
    }
    _has_bits_[0] |= 0x00000080u;
  } else {
    _has_bits_[0] &= ~0x00000080u;
  }
  projection_ = projection;
  // @@protoc_insertion_point(field_set_allocated:civ.hdmap.Header.projection)
}

// optional bytes district = 4;
inline bool Header::_internal_has_district() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Header::has_district() const {
  return _internal_has_district();
}
inline void Header::clear_district() {
  district_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& Header::district() const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Header.district)
  return _internal_district();
}
inline void Header::set_district(const std::string& value) {
  _internal_set_district(value);
  // @@protoc_insertion_point(field_set:civ.hdmap.Header.district)
}
inline std::string* Header::mutable_district() {
  // @@protoc_insertion_point(field_mutable:civ.hdmap.Header.district)
  return _internal_mutable_district();
}
inline const std::string& Header::_internal_district() const {
  return district_.Get();
}
inline void Header::_internal_set_district(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  district_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Header::set_district(std::string&& value) {
  _has_bits_[0] |= 0x00000004u;
  district_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:civ.hdmap.Header.district)
}
inline void Header::set_district(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000004u;
  district_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:civ.hdmap.Header.district)
}
inline void Header::set_district(const void* value,
    size_t size) {
  _has_bits_[0] |= 0x00000004u;
  district_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:civ.hdmap.Header.district)
}
inline std::string* Header::_internal_mutable_district() {
  _has_bits_[0] |= 0x00000004u;
  return district_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Header::release_district() {
  // @@protoc_insertion_point(field_release:civ.hdmap.Header.district)
  if (!_internal_has_district()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return district_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Header::set_allocated_district(std::string* district) {
  if (district != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  district_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), district,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:civ.hdmap.Header.district)
}

// optional bytes generation = 5;
inline bool Header::_internal_has_generation() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Header::has_generation() const {
  return _internal_has_generation();
}
inline void Header::clear_generation() {
  generation_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000008u;
}
inline const std::string& Header::generation() const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Header.generation)
  return _internal_generation();
}
inline void Header::set_generation(const std::string& value) {
  _internal_set_generation(value);
  // @@protoc_insertion_point(field_set:civ.hdmap.Header.generation)
}
inline std::string* Header::mutable_generation() {
  // @@protoc_insertion_point(field_mutable:civ.hdmap.Header.generation)
  return _internal_mutable_generation();
}
inline const std::string& Header::_internal_generation() const {
  return generation_.Get();
}
inline void Header::_internal_set_generation(const std::string& value) {
  _has_bits_[0] |= 0x00000008u;
  generation_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Header::set_generation(std::string&& value) {
  _has_bits_[0] |= 0x00000008u;
  generation_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:civ.hdmap.Header.generation)
}
inline void Header::set_generation(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000008u;
  generation_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:civ.hdmap.Header.generation)
}
inline void Header::set_generation(const void* value,
    size_t size) {
  _has_bits_[0] |= 0x00000008u;
  generation_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:civ.hdmap.Header.generation)
}
inline std::string* Header::_internal_mutable_generation() {
  _has_bits_[0] |= 0x00000008u;
  return generation_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Header::release_generation() {
  // @@protoc_insertion_point(field_release:civ.hdmap.Header.generation)
  if (!_internal_has_generation()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000008u;
  return generation_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Header::set_allocated_generation(std::string* generation) {
  if (generation != nullptr) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  generation_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), generation,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:civ.hdmap.Header.generation)
}

// optional bytes rev_major = 6;
inline bool Header::_internal_has_rev_major() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Header::has_rev_major() const {
  return _internal_has_rev_major();
}
inline void Header::clear_rev_major() {
  rev_major_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000010u;
}
inline const std::string& Header::rev_major() const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Header.rev_major)
  return _internal_rev_major();
}
inline void Header::set_rev_major(const std::string& value) {
  _internal_set_rev_major(value);
  // @@protoc_insertion_point(field_set:civ.hdmap.Header.rev_major)
}
inline std::string* Header::mutable_rev_major() {
  // @@protoc_insertion_point(field_mutable:civ.hdmap.Header.rev_major)
  return _internal_mutable_rev_major();
}
inline const std::string& Header::_internal_rev_major() const {
  return rev_major_.Get();
}
inline void Header::_internal_set_rev_major(const std::string& value) {
  _has_bits_[0] |= 0x00000010u;
  rev_major_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Header::set_rev_major(std::string&& value) {
  _has_bits_[0] |= 0x00000010u;
  rev_major_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:civ.hdmap.Header.rev_major)
}
inline void Header::set_rev_major(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000010u;
  rev_major_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:civ.hdmap.Header.rev_major)
}
inline void Header::set_rev_major(const void* value,
    size_t size) {
  _has_bits_[0] |= 0x00000010u;
  rev_major_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:civ.hdmap.Header.rev_major)
}
inline std::string* Header::_internal_mutable_rev_major() {
  _has_bits_[0] |= 0x00000010u;
  return rev_major_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Header::release_rev_major() {
  // @@protoc_insertion_point(field_release:civ.hdmap.Header.rev_major)
  if (!_internal_has_rev_major()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000010u;
  return rev_major_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Header::set_allocated_rev_major(std::string* rev_major) {
  if (rev_major != nullptr) {
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  rev_major_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), rev_major,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:civ.hdmap.Header.rev_major)
}

// optional bytes rev_minor = 7;
inline bool Header::_internal_has_rev_minor() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool Header::has_rev_minor() const {
  return _internal_has_rev_minor();
}
inline void Header::clear_rev_minor() {
  rev_minor_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000020u;
}
inline const std::string& Header::rev_minor() const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Header.rev_minor)
  return _internal_rev_minor();
}
inline void Header::set_rev_minor(const std::string& value) {
  _internal_set_rev_minor(value);
  // @@protoc_insertion_point(field_set:civ.hdmap.Header.rev_minor)
}
inline std::string* Header::mutable_rev_minor() {
  // @@protoc_insertion_point(field_mutable:civ.hdmap.Header.rev_minor)
  return _internal_mutable_rev_minor();
}
inline const std::string& Header::_internal_rev_minor() const {
  return rev_minor_.Get();
}
inline void Header::_internal_set_rev_minor(const std::string& value) {
  _has_bits_[0] |= 0x00000020u;
  rev_minor_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Header::set_rev_minor(std::string&& value) {
  _has_bits_[0] |= 0x00000020u;
  rev_minor_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:civ.hdmap.Header.rev_minor)
}
inline void Header::set_rev_minor(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000020u;
  rev_minor_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:civ.hdmap.Header.rev_minor)
}
inline void Header::set_rev_minor(const void* value,
    size_t size) {
  _has_bits_[0] |= 0x00000020u;
  rev_minor_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:civ.hdmap.Header.rev_minor)
}
inline std::string* Header::_internal_mutable_rev_minor() {
  _has_bits_[0] |= 0x00000020u;
  return rev_minor_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Header::release_rev_minor() {
  // @@protoc_insertion_point(field_release:civ.hdmap.Header.rev_minor)
  if (!_internal_has_rev_minor()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000020u;
  return rev_minor_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Header::set_allocated_rev_minor(std::string* rev_minor) {
  if (rev_minor != nullptr) {
    _has_bits_[0] |= 0x00000020u;
  } else {
    _has_bits_[0] &= ~0x00000020u;
  }
  rev_minor_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), rev_minor,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:civ.hdmap.Header.rev_minor)
}

// optional double left = 8;
inline bool Header::_internal_has_left() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool Header::has_left() const {
  return _internal_has_left();
}
inline void Header::clear_left() {
  left_ = 0;
  _has_bits_[0] &= ~0x00000100u;
}
inline double Header::_internal_left() const {
  return left_;
}
inline double Header::left() const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Header.left)
  return _internal_left();
}
inline void Header::_internal_set_left(double value) {
  _has_bits_[0] |= 0x00000100u;
  left_ = value;
}
inline void Header::set_left(double value) {
  _internal_set_left(value);
  // @@protoc_insertion_point(field_set:civ.hdmap.Header.left)
}

// optional double top = 9;
inline bool Header::_internal_has_top() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool Header::has_top() const {
  return _internal_has_top();
}
inline void Header::clear_top() {
  top_ = 0;
  _has_bits_[0] &= ~0x00000200u;
}
inline double Header::_internal_top() const {
  return top_;
}
inline double Header::top() const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Header.top)
  return _internal_top();
}
inline void Header::_internal_set_top(double value) {
  _has_bits_[0] |= 0x00000200u;
  top_ = value;
}
inline void Header::set_top(double value) {
  _internal_set_top(value);
  // @@protoc_insertion_point(field_set:civ.hdmap.Header.top)
}

// optional double right = 10;
inline bool Header::_internal_has_right() const {
  bool value = (_has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline bool Header::has_right() const {
  return _internal_has_right();
}
inline void Header::clear_right() {
  right_ = 0;
  _has_bits_[0] &= ~0x00000400u;
}
inline double Header::_internal_right() const {
  return right_;
}
inline double Header::right() const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Header.right)
  return _internal_right();
}
inline void Header::_internal_set_right(double value) {
  _has_bits_[0] |= 0x00000400u;
  right_ = value;
}
inline void Header::set_right(double value) {
  _internal_set_right(value);
  // @@protoc_insertion_point(field_set:civ.hdmap.Header.right)
}

// optional double bottom = 11;
inline bool Header::_internal_has_bottom() const {
  bool value = (_has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline bool Header::has_bottom() const {
  return _internal_has_bottom();
}
inline void Header::clear_bottom() {
  bottom_ = 0;
  _has_bits_[0] &= ~0x00000800u;
}
inline double Header::_internal_bottom() const {
  return bottom_;
}
inline double Header::bottom() const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Header.bottom)
  return _internal_bottom();
}
inline void Header::_internal_set_bottom(double value) {
  _has_bits_[0] |= 0x00000800u;
  bottom_ = value;
}
inline void Header::set_bottom(double value) {
  _internal_set_bottom(value);
  // @@protoc_insertion_point(field_set:civ.hdmap.Header.bottom)
}

// optional bytes vendor = 12;
inline bool Header::_internal_has_vendor() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool Header::has_vendor() const {
  return _internal_has_vendor();
}
inline void Header::clear_vendor() {
  vendor_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000040u;
}
inline const std::string& Header::vendor() const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Header.vendor)
  return _internal_vendor();
}
inline void Header::set_vendor(const std::string& value) {
  _internal_set_vendor(value);
  // @@protoc_insertion_point(field_set:civ.hdmap.Header.vendor)
}
inline std::string* Header::mutable_vendor() {
  // @@protoc_insertion_point(field_mutable:civ.hdmap.Header.vendor)
  return _internal_mutable_vendor();
}
inline const std::string& Header::_internal_vendor() const {
  return vendor_.Get();
}
inline void Header::_internal_set_vendor(const std::string& value) {
  _has_bits_[0] |= 0x00000040u;
  vendor_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Header::set_vendor(std::string&& value) {
  _has_bits_[0] |= 0x00000040u;
  vendor_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:civ.hdmap.Header.vendor)
}
inline void Header::set_vendor(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000040u;
  vendor_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:civ.hdmap.Header.vendor)
}
inline void Header::set_vendor(const void* value,
    size_t size) {
  _has_bits_[0] |= 0x00000040u;
  vendor_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:civ.hdmap.Header.vendor)
}
inline std::string* Header::_internal_mutable_vendor() {
  _has_bits_[0] |= 0x00000040u;
  return vendor_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Header::release_vendor() {
  // @@protoc_insertion_point(field_release:civ.hdmap.Header.vendor)
  if (!_internal_has_vendor()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000040u;
  return vendor_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Header::set_allocated_vendor(std::string* vendor) {
  if (vendor != nullptr) {
    _has_bits_[0] |= 0x00000040u;
  } else {
    _has_bits_[0] &= ~0x00000040u;
  }
  vendor_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), vendor,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:civ.hdmap.Header.vendor)
}

// -------------------------------------------------------------------

// Map

// optional .civ.hdmap.Header header = 1;
inline bool Map::_internal_has_header() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || header_ != nullptr);
  return value;
}
inline bool Map::has_header() const {
  return _internal_has_header();
}
inline void Map::clear_header() {
  if (header_ != nullptr) header_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::civ::hdmap::Header& Map::_internal_header() const {
  const ::civ::hdmap::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::civ::hdmap::Header&>(
      ::civ::hdmap::_Header_default_instance_);
}
inline const ::civ::hdmap::Header& Map::header() const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Map.header)
  return _internal_header();
}
inline void Map::unsafe_arena_set_allocated_header(
    ::civ::hdmap::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:civ.hdmap.Map.header)
}
inline ::civ::hdmap::Header* Map::release_header() {
  _has_bits_[0] &= ~0x00000001u;
  ::civ::hdmap::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::civ::hdmap::Header* Map::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:civ.hdmap.Map.header)
  _has_bits_[0] &= ~0x00000001u;
  ::civ::hdmap::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::civ::hdmap::Header* Map::_internal_mutable_header() {
  _has_bits_[0] |= 0x00000001u;
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::civ::hdmap::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::civ::hdmap::Header* Map::mutable_header() {
  // @@protoc_insertion_point(field_mutable:civ.hdmap.Map.header)
  return _internal_mutable_header();
}
inline void Map::set_allocated_header(::civ::hdmap::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete header_;
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(header);
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:civ.hdmap.Map.header)
}

// repeated .civ.hdmap.Crosswalk crosswalk = 2;
inline int Map::_internal_crosswalk_size() const {
  return crosswalk_.size();
}
inline int Map::crosswalk_size() const {
  return _internal_crosswalk_size();
}
inline ::civ::hdmap::Crosswalk* Map::mutable_crosswalk(int index) {
  // @@protoc_insertion_point(field_mutable:civ.hdmap.Map.crosswalk)
  return crosswalk_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Crosswalk >*
Map::mutable_crosswalk() {
  // @@protoc_insertion_point(field_mutable_list:civ.hdmap.Map.crosswalk)
  return &crosswalk_;
}
inline const ::civ::hdmap::Crosswalk& Map::_internal_crosswalk(int index) const {
  return crosswalk_.Get(index);
}
inline const ::civ::hdmap::Crosswalk& Map::crosswalk(int index) const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Map.crosswalk)
  return _internal_crosswalk(index);
}
inline ::civ::hdmap::Crosswalk* Map::_internal_add_crosswalk() {
  return crosswalk_.Add();
}
inline ::civ::hdmap::Crosswalk* Map::add_crosswalk() {
  // @@protoc_insertion_point(field_add:civ.hdmap.Map.crosswalk)
  return _internal_add_crosswalk();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Crosswalk >&
Map::crosswalk() const {
  // @@protoc_insertion_point(field_list:civ.hdmap.Map.crosswalk)
  return crosswalk_;
}

// repeated .civ.hdmap.Junction junction = 3;
inline int Map::_internal_junction_size() const {
  return junction_.size();
}
inline int Map::junction_size() const {
  return _internal_junction_size();
}
inline ::civ::hdmap::Junction* Map::mutable_junction(int index) {
  // @@protoc_insertion_point(field_mutable:civ.hdmap.Map.junction)
  return junction_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Junction >*
Map::mutable_junction() {
  // @@protoc_insertion_point(field_mutable_list:civ.hdmap.Map.junction)
  return &junction_;
}
inline const ::civ::hdmap::Junction& Map::_internal_junction(int index) const {
  return junction_.Get(index);
}
inline const ::civ::hdmap::Junction& Map::junction(int index) const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Map.junction)
  return _internal_junction(index);
}
inline ::civ::hdmap::Junction* Map::_internal_add_junction() {
  return junction_.Add();
}
inline ::civ::hdmap::Junction* Map::add_junction() {
  // @@protoc_insertion_point(field_add:civ.hdmap.Map.junction)
  return _internal_add_junction();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Junction >&
Map::junction() const {
  // @@protoc_insertion_point(field_list:civ.hdmap.Map.junction)
  return junction_;
}

// repeated .civ.hdmap.Lane lane = 4;
inline int Map::_internal_lane_size() const {
  return lane_.size();
}
inline int Map::lane_size() const {
  return _internal_lane_size();
}
inline ::civ::hdmap::Lane* Map::mutable_lane(int index) {
  // @@protoc_insertion_point(field_mutable:civ.hdmap.Map.lane)
  return lane_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Lane >*
Map::mutable_lane() {
  // @@protoc_insertion_point(field_mutable_list:civ.hdmap.Map.lane)
  return &lane_;
}
inline const ::civ::hdmap::Lane& Map::_internal_lane(int index) const {
  return lane_.Get(index);
}
inline const ::civ::hdmap::Lane& Map::lane(int index) const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Map.lane)
  return _internal_lane(index);
}
inline ::civ::hdmap::Lane* Map::_internal_add_lane() {
  return lane_.Add();
}
inline ::civ::hdmap::Lane* Map::add_lane() {
  // @@protoc_insertion_point(field_add:civ.hdmap.Map.lane)
  return _internal_add_lane();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Lane >&
Map::lane() const {
  // @@protoc_insertion_point(field_list:civ.hdmap.Map.lane)
  return lane_;
}

// repeated .civ.hdmap.StopSign stop_sign = 5;
inline int Map::_internal_stop_sign_size() const {
  return stop_sign_.size();
}
inline int Map::stop_sign_size() const {
  return _internal_stop_sign_size();
}
inline ::civ::hdmap::StopSign* Map::mutable_stop_sign(int index) {
  // @@protoc_insertion_point(field_mutable:civ.hdmap.Map.stop_sign)
  return stop_sign_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::StopSign >*
Map::mutable_stop_sign() {
  // @@protoc_insertion_point(field_mutable_list:civ.hdmap.Map.stop_sign)
  return &stop_sign_;
}
inline const ::civ::hdmap::StopSign& Map::_internal_stop_sign(int index) const {
  return stop_sign_.Get(index);
}
inline const ::civ::hdmap::StopSign& Map::stop_sign(int index) const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Map.stop_sign)
  return _internal_stop_sign(index);
}
inline ::civ::hdmap::StopSign* Map::_internal_add_stop_sign() {
  return stop_sign_.Add();
}
inline ::civ::hdmap::StopSign* Map::add_stop_sign() {
  // @@protoc_insertion_point(field_add:civ.hdmap.Map.stop_sign)
  return _internal_add_stop_sign();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::StopSign >&
Map::stop_sign() const {
  // @@protoc_insertion_point(field_list:civ.hdmap.Map.stop_sign)
  return stop_sign_;
}

// repeated .civ.hdmap.Signal signal = 6;
inline int Map::_internal_signal_size() const {
  return signal_.size();
}
inline int Map::signal_size() const {
  return _internal_signal_size();
}
inline ::civ::hdmap::Signal* Map::mutable_signal(int index) {
  // @@protoc_insertion_point(field_mutable:civ.hdmap.Map.signal)
  return signal_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Signal >*
Map::mutable_signal() {
  // @@protoc_insertion_point(field_mutable_list:civ.hdmap.Map.signal)
  return &signal_;
}
inline const ::civ::hdmap::Signal& Map::_internal_signal(int index) const {
  return signal_.Get(index);
}
inline const ::civ::hdmap::Signal& Map::signal(int index) const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Map.signal)
  return _internal_signal(index);
}
inline ::civ::hdmap::Signal* Map::_internal_add_signal() {
  return signal_.Add();
}
inline ::civ::hdmap::Signal* Map::add_signal() {
  // @@protoc_insertion_point(field_add:civ.hdmap.Map.signal)
  return _internal_add_signal();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Signal >&
Map::signal() const {
  // @@protoc_insertion_point(field_list:civ.hdmap.Map.signal)
  return signal_;
}

// repeated .civ.hdmap.YieldSign yield = 7;
inline int Map::_internal_yield_size() const {
  return yield_.size();
}
inline int Map::yield_size() const {
  return _internal_yield_size();
}
inline ::civ::hdmap::YieldSign* Map::mutable_yield(int index) {
  // @@protoc_insertion_point(field_mutable:civ.hdmap.Map.yield)
  return yield_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::YieldSign >*
Map::mutable_yield() {
  // @@protoc_insertion_point(field_mutable_list:civ.hdmap.Map.yield)
  return &yield_;
}
inline const ::civ::hdmap::YieldSign& Map::_internal_yield(int index) const {
  return yield_.Get(index);
}
inline const ::civ::hdmap::YieldSign& Map::yield(int index) const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Map.yield)
  return _internal_yield(index);
}
inline ::civ::hdmap::YieldSign* Map::_internal_add_yield() {
  return yield_.Add();
}
inline ::civ::hdmap::YieldSign* Map::add_yield() {
  // @@protoc_insertion_point(field_add:civ.hdmap.Map.yield)
  return _internal_add_yield();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::YieldSign >&
Map::yield() const {
  // @@protoc_insertion_point(field_list:civ.hdmap.Map.yield)
  return yield_;
}

// repeated .civ.hdmap.Overlap overlap = 8;
inline int Map::_internal_overlap_size() const {
  return overlap_.size();
}
inline int Map::overlap_size() const {
  return _internal_overlap_size();
}
inline ::civ::hdmap::Overlap* Map::mutable_overlap(int index) {
  // @@protoc_insertion_point(field_mutable:civ.hdmap.Map.overlap)
  return overlap_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Overlap >*
Map::mutable_overlap() {
  // @@protoc_insertion_point(field_mutable_list:civ.hdmap.Map.overlap)
  return &overlap_;
}
inline const ::civ::hdmap::Overlap& Map::_internal_overlap(int index) const {
  return overlap_.Get(index);
}
inline const ::civ::hdmap::Overlap& Map::overlap(int index) const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Map.overlap)
  return _internal_overlap(index);
}
inline ::civ::hdmap::Overlap* Map::_internal_add_overlap() {
  return overlap_.Add();
}
inline ::civ::hdmap::Overlap* Map::add_overlap() {
  // @@protoc_insertion_point(field_add:civ.hdmap.Map.overlap)
  return _internal_add_overlap();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Overlap >&
Map::overlap() const {
  // @@protoc_insertion_point(field_list:civ.hdmap.Map.overlap)
  return overlap_;
}

// repeated .civ.hdmap.ClearArea clear_area = 9;
inline int Map::_internal_clear_area_size() const {
  return clear_area_.size();
}
inline int Map::clear_area_size() const {
  return _internal_clear_area_size();
}
inline ::civ::hdmap::ClearArea* Map::mutable_clear_area(int index) {
  // @@protoc_insertion_point(field_mutable:civ.hdmap.Map.clear_area)
  return clear_area_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::ClearArea >*
Map::mutable_clear_area() {
  // @@protoc_insertion_point(field_mutable_list:civ.hdmap.Map.clear_area)
  return &clear_area_;
}
inline const ::civ::hdmap::ClearArea& Map::_internal_clear_area(int index) const {
  return clear_area_.Get(index);
}
inline const ::civ::hdmap::ClearArea& Map::clear_area(int index) const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Map.clear_area)
  return _internal_clear_area(index);
}
inline ::civ::hdmap::ClearArea* Map::_internal_add_clear_area() {
  return clear_area_.Add();
}
inline ::civ::hdmap::ClearArea* Map::add_clear_area() {
  // @@protoc_insertion_point(field_add:civ.hdmap.Map.clear_area)
  return _internal_add_clear_area();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::ClearArea >&
Map::clear_area() const {
  // @@protoc_insertion_point(field_list:civ.hdmap.Map.clear_area)
  return clear_area_;
}

// repeated .civ.hdmap.SpeedBump speed_bump = 10;
inline int Map::_internal_speed_bump_size() const {
  return speed_bump_.size();
}
inline int Map::speed_bump_size() const {
  return _internal_speed_bump_size();
}
inline ::civ::hdmap::SpeedBump* Map::mutable_speed_bump(int index) {
  // @@protoc_insertion_point(field_mutable:civ.hdmap.Map.speed_bump)
  return speed_bump_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::SpeedBump >*
Map::mutable_speed_bump() {
  // @@protoc_insertion_point(field_mutable_list:civ.hdmap.Map.speed_bump)
  return &speed_bump_;
}
inline const ::civ::hdmap::SpeedBump& Map::_internal_speed_bump(int index) const {
  return speed_bump_.Get(index);
}
inline const ::civ::hdmap::SpeedBump& Map::speed_bump(int index) const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Map.speed_bump)
  return _internal_speed_bump(index);
}
inline ::civ::hdmap::SpeedBump* Map::_internal_add_speed_bump() {
  return speed_bump_.Add();
}
inline ::civ::hdmap::SpeedBump* Map::add_speed_bump() {
  // @@protoc_insertion_point(field_add:civ.hdmap.Map.speed_bump)
  return _internal_add_speed_bump();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::SpeedBump >&
Map::speed_bump() const {
  // @@protoc_insertion_point(field_list:civ.hdmap.Map.speed_bump)
  return speed_bump_;
}

// repeated .civ.hdmap.Road road = 11;
inline int Map::_internal_road_size() const {
  return road_.size();
}
inline int Map::road_size() const {
  return _internal_road_size();
}
inline ::civ::hdmap::Road* Map::mutable_road(int index) {
  // @@protoc_insertion_point(field_mutable:civ.hdmap.Map.road)
  return road_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Road >*
Map::mutable_road() {
  // @@protoc_insertion_point(field_mutable_list:civ.hdmap.Map.road)
  return &road_;
}
inline const ::civ::hdmap::Road& Map::_internal_road(int index) const {
  return road_.Get(index);
}
inline const ::civ::hdmap::Road& Map::road(int index) const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Map.road)
  return _internal_road(index);
}
inline ::civ::hdmap::Road* Map::_internal_add_road() {
  return road_.Add();
}
inline ::civ::hdmap::Road* Map::add_road() {
  // @@protoc_insertion_point(field_add:civ.hdmap.Map.road)
  return _internal_add_road();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::Road >&
Map::road() const {
  // @@protoc_insertion_point(field_list:civ.hdmap.Map.road)
  return road_;
}

// repeated .civ.hdmap.ParkingSpace parking_space = 12;
inline int Map::_internal_parking_space_size() const {
  return parking_space_.size();
}
inline int Map::parking_space_size() const {
  return _internal_parking_space_size();
}
inline ::civ::hdmap::ParkingSpace* Map::mutable_parking_space(int index) {
  // @@protoc_insertion_point(field_mutable:civ.hdmap.Map.parking_space)
  return parking_space_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::ParkingSpace >*
Map::mutable_parking_space() {
  // @@protoc_insertion_point(field_mutable_list:civ.hdmap.Map.parking_space)
  return &parking_space_;
}
inline const ::civ::hdmap::ParkingSpace& Map::_internal_parking_space(int index) const {
  return parking_space_.Get(index);
}
inline const ::civ::hdmap::ParkingSpace& Map::parking_space(int index) const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Map.parking_space)
  return _internal_parking_space(index);
}
inline ::civ::hdmap::ParkingSpace* Map::_internal_add_parking_space() {
  return parking_space_.Add();
}
inline ::civ::hdmap::ParkingSpace* Map::add_parking_space() {
  // @@protoc_insertion_point(field_add:civ.hdmap.Map.parking_space)
  return _internal_add_parking_space();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::ParkingSpace >&
Map::parking_space() const {
  // @@protoc_insertion_point(field_list:civ.hdmap.Map.parking_space)
  return parking_space_;
}

// repeated .civ.hdmap.PNCJunction pnc_junction = 13;
inline int Map::_internal_pnc_junction_size() const {
  return pnc_junction_.size();
}
inline int Map::pnc_junction_size() const {
  return _internal_pnc_junction_size();
}
inline ::civ::hdmap::PNCJunction* Map::mutable_pnc_junction(int index) {
  // @@protoc_insertion_point(field_mutable:civ.hdmap.Map.pnc_junction)
  return pnc_junction_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::PNCJunction >*
Map::mutable_pnc_junction() {
  // @@protoc_insertion_point(field_mutable_list:civ.hdmap.Map.pnc_junction)
  return &pnc_junction_;
}
inline const ::civ::hdmap::PNCJunction& Map::_internal_pnc_junction(int index) const {
  return pnc_junction_.Get(index);
}
inline const ::civ::hdmap::PNCJunction& Map::pnc_junction(int index) const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Map.pnc_junction)
  return _internal_pnc_junction(index);
}
inline ::civ::hdmap::PNCJunction* Map::_internal_add_pnc_junction() {
  return pnc_junction_.Add();
}
inline ::civ::hdmap::PNCJunction* Map::add_pnc_junction() {
  // @@protoc_insertion_point(field_add:civ.hdmap.Map.pnc_junction)
  return _internal_add_pnc_junction();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::PNCJunction >&
Map::pnc_junction() const {
  // @@protoc_insertion_point(field_list:civ.hdmap.Map.pnc_junction)
  return pnc_junction_;
}

// repeated .civ.hdmap.RSU rsu = 14;
inline int Map::_internal_rsu_size() const {
  return rsu_.size();
}
inline int Map::rsu_size() const {
  return _internal_rsu_size();
}
inline ::civ::hdmap::RSU* Map::mutable_rsu(int index) {
  // @@protoc_insertion_point(field_mutable:civ.hdmap.Map.rsu)
  return rsu_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::RSU >*
Map::mutable_rsu() {
  // @@protoc_insertion_point(field_mutable_list:civ.hdmap.Map.rsu)
  return &rsu_;
}
inline const ::civ::hdmap::RSU& Map::_internal_rsu(int index) const {
  return rsu_.Get(index);
}
inline const ::civ::hdmap::RSU& Map::rsu(int index) const {
  // @@protoc_insertion_point(field_get:civ.hdmap.Map.rsu)
  return _internal_rsu(index);
}
inline ::civ::hdmap::RSU* Map::_internal_add_rsu() {
  return rsu_.Add();
}
inline ::civ::hdmap::RSU* Map::add_rsu() {
  // @@protoc_insertion_point(field_add:civ.hdmap.Map.rsu)
  return _internal_add_rsu();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::civ::hdmap::RSU >&
Map::rsu() const {
  // @@protoc_insertion_point(field_list:civ.hdmap.Map.rsu)
  return rsu_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace hdmap
}  // namespace civ

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_message_2fmap_2fproto_2fmap_2eproto
