// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message/map/proto/map_yield_sign.proto

#include "message/map/proto/map_yield_sign.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_message_2fmap_2fproto_2fmap_5fgeometry_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_Curve_message_2fmap_2fproto_2fmap_5fgeometry_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_message_2fmap_2fproto_2fmap_5fid_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Id_message_2fmap_2fproto_2fmap_5fid_2eproto;
namespace civ {
namespace hdmap {
class YieldSignDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<YieldSign> _instance;
} _YieldSign_default_instance_;
}  // namespace hdmap
}  // namespace civ
static void InitDefaultsscc_info_YieldSign_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::civ::hdmap::_YieldSign_default_instance_;
    new (ptr) ::civ::hdmap::YieldSign();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_YieldSign_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_YieldSign_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto}, {
      &scc_info_Id_message_2fmap_2fproto_2fmap_5fid_2eproto.base,
      &scc_info_Curve_message_2fmap_2fproto_2fmap_5fgeometry_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::civ::hdmap::YieldSign, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::civ::hdmap::YieldSign, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::civ::hdmap::YieldSign, id_),
  PROTOBUF_FIELD_OFFSET(::civ::hdmap::YieldSign, stop_line_),
  PROTOBUF_FIELD_OFFSET(::civ::hdmap::YieldSign, overlap_id_),
  0,
  ~0u,
  ~0u,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(::civ::hdmap::YieldSign)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::civ::hdmap::_YieldSign_default_instance_),
};

const char descriptor_table_protodef_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n&message/map/proto/map_yield_sign.proto"
  "\022\tciv.hdmap\032\036message/map/proto/map_id.pr"
  "oto\032$message/map/proto/map_geometry.prot"
  "o\"n\n\tYieldSign\022\031\n\002id\030\001 \001(\0132\r.civ.hdmap.I"
  "d\022#\n\tstop_line\030\002 \003(\0132\020.civ.hdmap.Curve\022!"
  "\n\noverlap_id\030\003 \003(\0132\r.civ.hdmap.Id"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto_deps[2] = {
  &::descriptor_table_message_2fmap_2fproto_2fmap_5fgeometry_2eproto,
  &::descriptor_table_message_2fmap_2fproto_2fmap_5fid_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto_sccs[1] = {
  &scc_info_YieldSign_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto = {
  false, false, descriptor_table_protodef_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto, "message/map/proto/map_yield_sign.proto", 233,
  &descriptor_table_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto_once, descriptor_table_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto_sccs, descriptor_table_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto_deps, 1, 2,
  schemas, file_default_instances, TableStruct_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto::offsets,
  file_level_metadata_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto, 1, file_level_enum_descriptors_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto, file_level_service_descriptors_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto)), true);
namespace civ {
namespace hdmap {

// ===================================================================

class YieldSign::_Internal {
 public:
  using HasBits = decltype(std::declval<YieldSign>()._has_bits_);
  static const ::civ::hdmap::Id& id(const YieldSign* msg);
  static void set_has_id(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::civ::hdmap::Id&
YieldSign::_Internal::id(const YieldSign* msg) {
  return *msg->id_;
}
void YieldSign::clear_id() {
  if (id_ != nullptr) id_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
void YieldSign::clear_stop_line() {
  stop_line_.Clear();
}
void YieldSign::clear_overlap_id() {
  overlap_id_.Clear();
}
YieldSign::YieldSign(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  stop_line_(arena),
  overlap_id_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:civ.hdmap.YieldSign)
}
YieldSign::YieldSign(const YieldSign& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_),
      stop_line_(from.stop_line_),
      overlap_id_(from.overlap_id_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_id()) {
    id_ = new ::civ::hdmap::Id(*from.id_);
  } else {
    id_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:civ.hdmap.YieldSign)
}

void YieldSign::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_YieldSign_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto.base);
  id_ = nullptr;
}

YieldSign::~YieldSign() {
  // @@protoc_insertion_point(destructor:civ.hdmap.YieldSign)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void YieldSign::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete id_;
}

void YieldSign::ArenaDtor(void* object) {
  YieldSign* _this = reinterpret_cast< YieldSign* >(object);
  (void)_this;
}
void YieldSign::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void YieldSign::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const YieldSign& YieldSign::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_YieldSign_message_2fmap_2fproto_2fmap_5fyield_5fsign_2eproto.base);
  return *internal_default_instance();
}


void YieldSign::Clear() {
// @@protoc_insertion_point(message_clear_start:civ.hdmap.YieldSign)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  stop_line_.Clear();
  overlap_id_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(id_ != nullptr);
    id_->Clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* YieldSign::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional .civ.hdmap.Id id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_id(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .civ.hdmap.Curve stop_line = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_stop_line(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .civ.hdmap.Id overlap_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_overlap_id(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* YieldSign::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:civ.hdmap.YieldSign)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .civ.hdmap.Id id = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::id(this), target, stream);
  }

  // repeated .civ.hdmap.Curve stop_line = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_stop_line_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_stop_line(i), target, stream);
  }

  // repeated .civ.hdmap.Id overlap_id = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_overlap_id_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, this->_internal_overlap_id(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:civ.hdmap.YieldSign)
  return target;
}

size_t YieldSign::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:civ.hdmap.YieldSign)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .civ.hdmap.Curve stop_line = 2;
  total_size += 1UL * this->_internal_stop_line_size();
  for (const auto& msg : this->stop_line_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .civ.hdmap.Id overlap_id = 3;
  total_size += 1UL * this->_internal_overlap_id_size();
  for (const auto& msg : this->overlap_id_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // optional .civ.hdmap.Id id = 1;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *id_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void YieldSign::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:civ.hdmap.YieldSign)
  GOOGLE_DCHECK_NE(&from, this);
  const YieldSign* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<YieldSign>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:civ.hdmap.YieldSign)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:civ.hdmap.YieldSign)
    MergeFrom(*source);
  }
}

void YieldSign::MergeFrom(const YieldSign& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:civ.hdmap.YieldSign)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  stop_line_.MergeFrom(from.stop_line_);
  overlap_id_.MergeFrom(from.overlap_id_);
  if (from._internal_has_id()) {
    _internal_mutable_id()->::civ::hdmap::Id::MergeFrom(from._internal_id());
  }
}

void YieldSign::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:civ.hdmap.YieldSign)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void YieldSign::CopyFrom(const YieldSign& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:civ.hdmap.YieldSign)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool YieldSign::IsInitialized() const {
  return true;
}

void YieldSign::InternalSwap(YieldSign* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  stop_line_.InternalSwap(&other->stop_line_);
  overlap_id_.InternalSwap(&other->overlap_id_);
  swap(id_, other->id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata YieldSign::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace hdmap
}  // namespace civ
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::civ::hdmap::YieldSign* Arena::CreateMaybeMessage< ::civ::hdmap::YieldSign >(Arena* arena) {
  return Arena::CreateMessageInternal< ::civ::hdmap::YieldSign >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
