// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message/drivers/imu/proto/imu.proto

#include "message/drivers/imu/proto/imu.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_message_2fcommon_2fproto_2fheader_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_Header_message_2fcommon_2fproto_2fheader_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_message_2fcommon_2fproto_2fgeometry_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Point3D_message_2fcommon_2fproto_2fgeometry_2eproto;
namespace civ {
namespace drivers {
namespace imu {
class CorrectedImuDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<CorrectedImu> _instance;
} _CorrectedImu_default_instance_;
}  // namespace imu
}  // namespace drivers
}  // namespace civ
static void InitDefaultsscc_info_CorrectedImu_message_2fdrivers_2fimu_2fproto_2fimu_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::civ::drivers::imu::_CorrectedImu_default_instance_;
    new (ptr) ::civ::drivers::imu::CorrectedImu();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_CorrectedImu_message_2fdrivers_2fimu_2fproto_2fimu_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_CorrectedImu_message_2fdrivers_2fimu_2fproto_2fimu_2eproto}, {
      &scc_info_Header_message_2fcommon_2fproto_2fheader_2eproto.base,
      &scc_info_Point3D_message_2fcommon_2fproto_2fgeometry_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_message_2fdrivers_2fimu_2fproto_2fimu_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_message_2fdrivers_2fimu_2fproto_2fimu_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_message_2fdrivers_2fimu_2fproto_2fimu_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_message_2fdrivers_2fimu_2fproto_2fimu_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::civ::drivers::imu::CorrectedImu, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::civ::drivers::imu::CorrectedImu, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::civ::drivers::imu::CorrectedImu, header_),
  PROTOBUF_FIELD_OFFSET(::civ::drivers::imu::CorrectedImu, measurement_time_),
  PROTOBUF_FIELD_OFFSET(::civ::drivers::imu::CorrectedImu, measurement_span_),
  PROTOBUF_FIELD_OFFSET(::civ::drivers::imu::CorrectedImu, linear_acceleration_),
  PROTOBUF_FIELD_OFFSET(::civ::drivers::imu::CorrectedImu, angular_velocity_),
  0,
  3,
  4,
  1,
  2,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 10, sizeof(::civ::drivers::imu::CorrectedImu)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::civ::drivers::imu::_CorrectedImu_default_instance_),
};

const char descriptor_table_protodef_message_2fdrivers_2fimu_2fproto_2fimu_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n#message/drivers/imu/proto/imu.proto\022\017c"
  "iv.drivers.imu\032#message/common/proto/geo"
  "metry.proto\032!message/common/proto/header"
  ".proto\"\312\001\n\014CorrectedImu\022\"\n\006header\030\001 \001(\0132"
  "\022.civ.common.Header\022\030\n\020measurement_time\030"
  "\002 \001(\001\022\033\n\020measurement_span\030\003 \001(\002:\0010\0220\n\023li"
  "near_acceleration\030\004 \001(\0132\023.civ.common.Poi"
  "nt3D\022-\n\020angular_velocity\030\005 \001(\0132\023.civ.com"
  "mon.Point3D"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_message_2fdrivers_2fimu_2fproto_2fimu_2eproto_deps[2] = {
  &::descriptor_table_message_2fcommon_2fproto_2fgeometry_2eproto,
  &::descriptor_table_message_2fcommon_2fproto_2fheader_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_message_2fdrivers_2fimu_2fproto_2fimu_2eproto_sccs[1] = {
  &scc_info_CorrectedImu_message_2fdrivers_2fimu_2fproto_2fimu_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_message_2fdrivers_2fimu_2fproto_2fimu_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_2fdrivers_2fimu_2fproto_2fimu_2eproto = {
  false, false, descriptor_table_protodef_message_2fdrivers_2fimu_2fproto_2fimu_2eproto, "message/drivers/imu/proto/imu.proto", 331,
  &descriptor_table_message_2fdrivers_2fimu_2fproto_2fimu_2eproto_once, descriptor_table_message_2fdrivers_2fimu_2fproto_2fimu_2eproto_sccs, descriptor_table_message_2fdrivers_2fimu_2fproto_2fimu_2eproto_deps, 1, 2,
  schemas, file_default_instances, TableStruct_message_2fdrivers_2fimu_2fproto_2fimu_2eproto::offsets,
  file_level_metadata_message_2fdrivers_2fimu_2fproto_2fimu_2eproto, 1, file_level_enum_descriptors_message_2fdrivers_2fimu_2fproto_2fimu_2eproto, file_level_service_descriptors_message_2fdrivers_2fimu_2fproto_2fimu_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_message_2fdrivers_2fimu_2fproto_2fimu_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_message_2fdrivers_2fimu_2fproto_2fimu_2eproto)), true);
namespace civ {
namespace drivers {
namespace imu {

// ===================================================================

class CorrectedImu::_Internal {
 public:
  using HasBits = decltype(std::declval<CorrectedImu>()._has_bits_);
  static const ::civ::common::Header& header(const CorrectedImu* msg);
  static void set_has_header(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_measurement_time(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_measurement_span(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static const ::civ::common::Point3D& linear_acceleration(const CorrectedImu* msg);
  static void set_has_linear_acceleration(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::civ::common::Point3D& angular_velocity(const CorrectedImu* msg);
  static void set_has_angular_velocity(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

const ::civ::common::Header&
CorrectedImu::_Internal::header(const CorrectedImu* msg) {
  return *msg->header_;
}
const ::civ::common::Point3D&
CorrectedImu::_Internal::linear_acceleration(const CorrectedImu* msg) {
  return *msg->linear_acceleration_;
}
const ::civ::common::Point3D&
CorrectedImu::_Internal::angular_velocity(const CorrectedImu* msg) {
  return *msg->angular_velocity_;
}
void CorrectedImu::clear_header() {
  if (header_ != nullptr) header_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
void CorrectedImu::clear_linear_acceleration() {
  if (linear_acceleration_ != nullptr) linear_acceleration_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
void CorrectedImu::clear_angular_velocity() {
  if (angular_velocity_ != nullptr) angular_velocity_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
CorrectedImu::CorrectedImu(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:civ.drivers.imu.CorrectedImu)
}
CorrectedImu::CorrectedImu(const CorrectedImu& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_header()) {
    header_ = new ::civ::common::Header(*from.header_);
  } else {
    header_ = nullptr;
  }
  if (from._internal_has_linear_acceleration()) {
    linear_acceleration_ = new ::civ::common::Point3D(*from.linear_acceleration_);
  } else {
    linear_acceleration_ = nullptr;
  }
  if (from._internal_has_angular_velocity()) {
    angular_velocity_ = new ::civ::common::Point3D(*from.angular_velocity_);
  } else {
    angular_velocity_ = nullptr;
  }
  ::memcpy(&measurement_time_, &from.measurement_time_,
    static_cast<size_t>(reinterpret_cast<char*>(&measurement_span_) -
    reinterpret_cast<char*>(&measurement_time_)) + sizeof(measurement_span_));
  // @@protoc_insertion_point(copy_constructor:civ.drivers.imu.CorrectedImu)
}

void CorrectedImu::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_CorrectedImu_message_2fdrivers_2fimu_2fproto_2fimu_2eproto.base);
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&header_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&measurement_span_) -
      reinterpret_cast<char*>(&header_)) + sizeof(measurement_span_));
}

CorrectedImu::~CorrectedImu() {
  // @@protoc_insertion_point(destructor:civ.drivers.imu.CorrectedImu)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void CorrectedImu::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete header_;
  if (this != internal_default_instance()) delete linear_acceleration_;
  if (this != internal_default_instance()) delete angular_velocity_;
}

void CorrectedImu::ArenaDtor(void* object) {
  CorrectedImu* _this = reinterpret_cast< CorrectedImu* >(object);
  (void)_this;
}
void CorrectedImu::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void CorrectedImu::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CorrectedImu& CorrectedImu::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_CorrectedImu_message_2fdrivers_2fimu_2fproto_2fimu_2eproto.base);
  return *internal_default_instance();
}


void CorrectedImu::Clear() {
// @@protoc_insertion_point(message_clear_start:civ.drivers.imu.CorrectedImu)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(header_ != nullptr);
      header_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(linear_acceleration_ != nullptr);
      linear_acceleration_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(angular_velocity_ != nullptr);
      angular_velocity_->Clear();
    }
  }
  if (cached_has_bits & 0x00000018u) {
    ::memset(&measurement_time_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&measurement_span_) -
        reinterpret_cast<char*>(&measurement_time_)) + sizeof(measurement_span_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CorrectedImu::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional .civ.common.Header header = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_header(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional double measurement_time = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 17)) {
          _Internal::set_has_measurement_time(&has_bits);
          measurement_time_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional float measurement_span = 3 [default = 0];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29)) {
          _Internal::set_has_measurement_span(&has_bits);
          measurement_span_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // optional .civ.common.Point3D linear_acceleration = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_linear_acceleration(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .civ.common.Point3D angular_velocity = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_angular_velocity(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* CorrectedImu::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:civ.drivers.imu.CorrectedImu)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .civ.common.Header header = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::header(this), target, stream);
  }

  // optional double measurement_time = 2;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(2, this->_internal_measurement_time(), target);
  }

  // optional float measurement_span = 3 [default = 0];
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(3, this->_internal_measurement_span(), target);
  }

  // optional .civ.common.Point3D linear_acceleration = 4;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::linear_acceleration(this), target, stream);
  }

  // optional .civ.common.Point3D angular_velocity = 5;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        5, _Internal::angular_velocity(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:civ.drivers.imu.CorrectedImu)
  return target;
}

size_t CorrectedImu::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:civ.drivers.imu.CorrectedImu)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    // optional .civ.common.Header header = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *header_);
    }

    // optional .civ.common.Point3D linear_acceleration = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *linear_acceleration_);
    }

    // optional .civ.common.Point3D angular_velocity = 5;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *angular_velocity_);
    }

    // optional double measurement_time = 2;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 8;
    }

    // optional float measurement_span = 3 [default = 0];
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + 4;
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CorrectedImu::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:civ.drivers.imu.CorrectedImu)
  GOOGLE_DCHECK_NE(&from, this);
  const CorrectedImu* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<CorrectedImu>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:civ.drivers.imu.CorrectedImu)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:civ.drivers.imu.CorrectedImu)
    MergeFrom(*source);
  }
}

void CorrectedImu::MergeFrom(const CorrectedImu& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:civ.drivers.imu.CorrectedImu)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_mutable_header()->::civ::common::Header::MergeFrom(from._internal_header());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_mutable_linear_acceleration()->::civ::common::Point3D::MergeFrom(from._internal_linear_acceleration());
    }
    if (cached_has_bits & 0x00000004u) {
      _internal_mutable_angular_velocity()->::civ::common::Point3D::MergeFrom(from._internal_angular_velocity());
    }
    if (cached_has_bits & 0x00000008u) {
      measurement_time_ = from.measurement_time_;
    }
    if (cached_has_bits & 0x00000010u) {
      measurement_span_ = from.measurement_span_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void CorrectedImu::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:civ.drivers.imu.CorrectedImu)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CorrectedImu::CopyFrom(const CorrectedImu& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:civ.drivers.imu.CorrectedImu)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CorrectedImu::IsInitialized() const {
  return true;
}

void CorrectedImu::InternalSwap(CorrectedImu* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CorrectedImu, measurement_span_)
      + sizeof(CorrectedImu::measurement_span_)
      - PROTOBUF_FIELD_OFFSET(CorrectedImu, header_)>(
          reinterpret_cast<char*>(&header_),
          reinterpret_cast<char*>(&other->header_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CorrectedImu::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace imu
}  // namespace drivers
}  // namespace civ
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::civ::drivers::imu::CorrectedImu* Arena::CreateMaybeMessage< ::civ::drivers::imu::CorrectedImu >(Arena* arena) {
  return Arena::CreateMessageInternal< ::civ::drivers::imu::CorrectedImu >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
