# ---- 配置打包相关 ----
set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_PACKAGE_VENDOR "SuzhouZhito")
#set(CPACK_PACKAGE_DESCRIPTION_FILE "${PROJECT_SOURCE_DIR}/INSTALL.md")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "zhito localization package")
#set(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/LICENSE")

# ---- 设置相关目标的位置 ----
if(NOT PACK_INSTALL_PREFIX)
    set(PACK_INSTALL_PREFIX "/opt/zhito" CACHE PATH "Package install path" FORCE)
endif()

set(CPACK_PACKAGING_INSTALL_PREFIX ${PACK_INSTALL_PREFIX})
set(CPACK_PACKAGE_DIRECTORY ${zhitoauto_BINARY_DIR}/pack)

set(CPACK_PACKAGE_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${PROJECT_VERSION_PATCH}")

set(CPACK_SOURCE_IGNORE_FILES "${PROJECT_BINARY_DIR};/.git/;.gitignore")
set(CPACK_SOURCE_GENERATOR "TGZ;ZIP")
set(CPACK_GENERATOR "TGZ;ZIP")

message(STATUS "CPack generators: ${CPACK_GENERATOR}")
if (UNIX)
    if(CMAKE_SYSTEM_NAME MATCHES Linux)
        list(APPEND CPACK_GENERATOR "DEB")
        set(CPACK_DEBIAN_PACKAGE_MAINTAINER "zhito-control-group")
        set(CPACK_DEBIAN_PACKAGE_SECTION "devel")
    endif()
endif()
include(CPack)
