# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: civloc/proto/civloc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='civloc/proto/civloc.proto',
  package='civ.civloc',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x63ivloc/proto/civloc.proto\x12\nciv.civloc\"\xdd\x01\n\x16PerceptionChanelConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12>\n\x06vendor\x18\x02 \x01(\x0e\x32).civ.civloc.PerceptionChanelConfig.Vendor:\x03SIM\x12\x13\n\x07rate_hz\x18\x03 \x01(\r:\x02\x31\x30\"`\n\x06Vendor\x12\n\n\x06OTHERS\x10\x00\x12\x07\n\x03SIM\x10\x01\x12\t\n\x05ZHITO\x10\x02\x12\x0c\n\x08MOBILEYE\x10\x03\x12\x0b\n\x07MAXIEYE\x10\x04\x12\x0e\n\nSMARTEREYE\x10\x05\x12\x0b\n\x07HORIZON\x10\x06\"N\n\x08TFConfig\x12\x1d\n\x15\x62roadcast_tf_frame_id\x18\t \x01(\t\x12#\n\x1b\x62roadcast_tf_child_frame_id\x18\n \x01(\t\"-\n\x0c\x43hanelConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07rate_hz\x18\x02 \x01(\r\"\x8d\x06\n\x0c\x43ivLocConfig\x12,\n\x07version\x18\x01 \x02(\t:\x1bzloc_component config 1.0.0\x12\x38\n\x04mode\x18\x02 \x01(\x0e\x32!.civ.civloc.CivLocConfig.WorkMode:\x07\x46orward\x12)\n\x07\x63hassis\x18\x08 \x02(\x0b\x32\x18.civ.civloc.ChanelConfig\x12(\n\x06\x63gi610\x18\x0c \x02(\x0b\x32\x18.civ.civloc.ChanelConfig\x12\x34\n\x12raw_cgi610_bestpos\x18\r \x02(\x0b\x32\x18.civ.civloc.ChanelConfig\x12\x34\n\x12raw_cgi610_bestvel\x18\x0e \x02(\x0b\x32\x18.civ.civloc.ChanelConfig\x12\x35\n\x13raw_cgi610_heading2\x18\x0f \x02(\x0b\x32\x18.civ.civloc.ChanelConfig\x12\x32\n\x10raw_wheeltec_imu\x18\x10 \x02(\x0b\x32\x18.civ.civloc.ChanelConfig\x12\x36\n\nperception\x18\x11 \x03(\x0b\x32\".civ.civloc.PerceptionChanelConfig\x12,\n\npointcloud\x18\x12 \x02(\x0b\x32\x18.civ.civloc.ChanelConfig\x12\x30\n\x0epointcloud_map\x18\x13 \x01(\x0b\x32\x18.civ.civloc.ChanelConfig\x12*\n\x08zloc_map\x18\x14 \x01(\x0b\x32\x18.civ.civloc.ChanelConfig\x12&\n\x04\x63pt7\x18\x15 \x01(\x0b\x32\x18.civ.civloc.ChanelConfig\x12+\n\tzloc_fuse\x18\x16 \x02(\x0b\x32\x18.civ.civloc.ChanelConfig\x12-\n\x0b\x66orward_cfg\x18\x17 \x02(\x0b\x32\x18.civ.civloc.ChanelConfig\"!\n\x08WorkMode\x12\x0b\n\x07\x46orward\x10\x00\x12\x08\n\x04\x46use\x10\x01'
)



_PERCEPTIONCHANELCONFIG_VENDOR = _descriptor.EnumDescriptor(
  name='Vendor',
  full_name='civ.civloc.PerceptionChanelConfig.Vendor',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OTHERS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SIM', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ZHITO', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOBILEYE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MAXIEYE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SMARTEREYE', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HORIZON', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=167,
  serialized_end=263,
)
_sym_db.RegisterEnumDescriptor(_PERCEPTIONCHANELCONFIG_VENDOR)

_CIVLOCCONFIG_WORKMODE = _descriptor.EnumDescriptor(
  name='WorkMode',
  full_name='civ.civloc.CivLocConfig.WorkMode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Forward', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Fuse', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=1141,
  serialized_end=1174,
)
_sym_db.RegisterEnumDescriptor(_CIVLOCCONFIG_WORKMODE)


_PERCEPTIONCHANELCONFIG = _descriptor.Descriptor(
  name='PerceptionChanelConfig',
  full_name='civ.civloc.PerceptionChanelConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='civ.civloc.PerceptionChanelConfig.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vendor', full_name='civ.civloc.PerceptionChanelConfig.vendor', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rate_hz', full_name='civ.civloc.PerceptionChanelConfig.rate_hz', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PERCEPTIONCHANELCONFIG_VENDOR,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=263,
)


_TFCONFIG = _descriptor.Descriptor(
  name='TFConfig',
  full_name='civ.civloc.TFConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='broadcast_tf_frame_id', full_name='civ.civloc.TFConfig.broadcast_tf_frame_id', index=0,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='broadcast_tf_child_frame_id', full_name='civ.civloc.TFConfig.broadcast_tf_child_frame_id', index=1,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=343,
)


_CHANELCONFIG = _descriptor.Descriptor(
  name='ChanelConfig',
  full_name='civ.civloc.ChanelConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='civ.civloc.ChanelConfig.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rate_hz', full_name='civ.civloc.ChanelConfig.rate_hz', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=390,
)


_CIVLOCCONFIG = _descriptor.Descriptor(
  name='CivLocConfig',
  full_name='civ.civloc.CivLocConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='civ.civloc.CivLocConfig.version', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=b"zloc_component config 1.0.0".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mode', full_name='civ.civloc.CivLocConfig.mode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chassis', full_name='civ.civloc.CivLocConfig.chassis', index=2,
      number=8, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cgi610', full_name='civ.civloc.CivLocConfig.cgi610', index=3,
      number=12, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='raw_cgi610_bestpos', full_name='civ.civloc.CivLocConfig.raw_cgi610_bestpos', index=4,
      number=13, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='raw_cgi610_bestvel', full_name='civ.civloc.CivLocConfig.raw_cgi610_bestvel', index=5,
      number=14, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='raw_cgi610_heading2', full_name='civ.civloc.CivLocConfig.raw_cgi610_heading2', index=6,
      number=15, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='raw_wheeltec_imu', full_name='civ.civloc.CivLocConfig.raw_wheeltec_imu', index=7,
      number=16, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='perception', full_name='civ.civloc.CivLocConfig.perception', index=8,
      number=17, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pointcloud', full_name='civ.civloc.CivLocConfig.pointcloud', index=9,
      number=18, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pointcloud_map', full_name='civ.civloc.CivLocConfig.pointcloud_map', index=10,
      number=19, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='zloc_map', full_name='civ.civloc.CivLocConfig.zloc_map', index=11,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cpt7', full_name='civ.civloc.CivLocConfig.cpt7', index=12,
      number=21, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='zloc_fuse', full_name='civ.civloc.CivLocConfig.zloc_fuse', index=13,
      number=22, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='forward_cfg', full_name='civ.civloc.CivLocConfig.forward_cfg', index=14,
      number=23, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CIVLOCCONFIG_WORKMODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=1174,
)

_PERCEPTIONCHANELCONFIG.fields_by_name['vendor'].enum_type = _PERCEPTIONCHANELCONFIG_VENDOR
_PERCEPTIONCHANELCONFIG_VENDOR.containing_type = _PERCEPTIONCHANELCONFIG
_CIVLOCCONFIG.fields_by_name['mode'].enum_type = _CIVLOCCONFIG_WORKMODE
_CIVLOCCONFIG.fields_by_name['chassis'].message_type = _CHANELCONFIG
_CIVLOCCONFIG.fields_by_name['cgi610'].message_type = _CHANELCONFIG
_CIVLOCCONFIG.fields_by_name['raw_cgi610_bestpos'].message_type = _CHANELCONFIG
_CIVLOCCONFIG.fields_by_name['raw_cgi610_bestvel'].message_type = _CHANELCONFIG
_CIVLOCCONFIG.fields_by_name['raw_cgi610_heading2'].message_type = _CHANELCONFIG
_CIVLOCCONFIG.fields_by_name['raw_wheeltec_imu'].message_type = _CHANELCONFIG
_CIVLOCCONFIG.fields_by_name['perception'].message_type = _PERCEPTIONCHANELCONFIG
_CIVLOCCONFIG.fields_by_name['pointcloud'].message_type = _CHANELCONFIG
_CIVLOCCONFIG.fields_by_name['pointcloud_map'].message_type = _CHANELCONFIG
_CIVLOCCONFIG.fields_by_name['zloc_map'].message_type = _CHANELCONFIG
_CIVLOCCONFIG.fields_by_name['cpt7'].message_type = _CHANELCONFIG
_CIVLOCCONFIG.fields_by_name['zloc_fuse'].message_type = _CHANELCONFIG
_CIVLOCCONFIG.fields_by_name['forward_cfg'].message_type = _CHANELCONFIG
_CIVLOCCONFIG_WORKMODE.containing_type = _CIVLOCCONFIG
DESCRIPTOR.message_types_by_name['PerceptionChanelConfig'] = _PERCEPTIONCHANELCONFIG
DESCRIPTOR.message_types_by_name['TFConfig'] = _TFCONFIG
DESCRIPTOR.message_types_by_name['ChanelConfig'] = _CHANELCONFIG
DESCRIPTOR.message_types_by_name['CivLocConfig'] = _CIVLOCCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PerceptionChanelConfig = _reflection.GeneratedProtocolMessageType('PerceptionChanelConfig', (_message.Message,), {
  'DESCRIPTOR' : _PERCEPTIONCHANELCONFIG,
  '__module__' : 'civloc.proto.civloc_pb2'
  # @@protoc_insertion_point(class_scope:civ.civloc.PerceptionChanelConfig)
  })
_sym_db.RegisterMessage(PerceptionChanelConfig)

TFConfig = _reflection.GeneratedProtocolMessageType('TFConfig', (_message.Message,), {
  'DESCRIPTOR' : _TFCONFIG,
  '__module__' : 'civloc.proto.civloc_pb2'
  # @@protoc_insertion_point(class_scope:civ.civloc.TFConfig)
  })
_sym_db.RegisterMessage(TFConfig)

ChanelConfig = _reflection.GeneratedProtocolMessageType('ChanelConfig', (_message.Message,), {
  'DESCRIPTOR' : _CHANELCONFIG,
  '__module__' : 'civloc.proto.civloc_pb2'
  # @@protoc_insertion_point(class_scope:civ.civloc.ChanelConfig)
  })
_sym_db.RegisterMessage(ChanelConfig)

CivLocConfig = _reflection.GeneratedProtocolMessageType('CivLocConfig', (_message.Message,), {
  'DESCRIPTOR' : _CIVLOCCONFIG,
  '__module__' : 'civloc.proto.civloc_pb2'
  # @@protoc_insertion_point(class_scope:civ.civloc.CivLocConfig)
  })
_sym_db.RegisterMessage(CivLocConfig)


# @@protoc_insertion_point(module_scope)
